# Generated by Django 4.2.9 on 2024-02-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Farmers",
        ),
    ]
